"""Plan Entity Module."""

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum


class StepStatus(StrEnum):
    """Execution status of an individual plan step."""

    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass(frozen=True)
class PlanStep:
    """Represents a discrete step inside an execution plan.

    Attributes:
        step_id: Unique identifier for the step.
        description: Description of what this step does.
        status: Current status of the execution.
        assigned_agent_id: Optional ID of the agent assigned to run this step.
        result: Optional result message or output from execution.
    """

    step_id: str
    description: str
    status: StepStatus = StepStatus.PENDING
    assigned_agent_id: str | None = None
    result: str | None = None


@dataclass(frozen=True)
class Plan:
    """Represents an execution roadmap generated by a planner to achieve a goal.

    Attributes:
        plan_id: Unique identifier for the plan.
        goal: The overall goal description.
        steps: Chronological list of steps to run.
        created_at: Time when the plan was created.
        updated_at: Time when the plan was last updated.
    """

    plan_id: str
    goal: str
    steps: list[PlanStep] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
